-- Acoperiș PRO — produse (seed pentru D1)
-- Rulează în: Dashboard → D1 → acoperispro-db → Console

INSERT OR REPLACE INTO products (id,cat,name,price,unit,badge,descr,specs,options,active) VALUES ('tm-clasic-05','tigla-metalica','Țiglă metalică Clasic 0.5mm',42.9,'mp','Best seller','Profil clasic din oțel 0.5mm cu strat de zinc și poliester mat, garanție 15 ani.','{"Grosime":"0.5 mm","Acoperire":"Poliester mat 25µm","Culoare":"Roșu cărămiziu RAL 8004","Garanție":"15 ani","Greutate":"4.8 kg/mp"}',NULL,1);
INSERT OR REPLACE INTO products (id,cat,name,price,unit,badge,descr,specs,options,active) VALUES ('tm-premium-galvalume','tigla-metalica','Țiglă metalică Premium Galvalume 0.6mm',58.5,'mp','Premium','Oțel Galvalume 0.6mm cu protecție anticorozivă superioară, ideal pentru zone cu vânt puternic.','{"Grosime":"0.6 mm","Acoperire":"Matt PU 35µm","Culoare":"Antracit RAL 7016","Garanție":"25 ani","Greutate":"5.4 kg/mp"}',NULL,1);
INSERT OR REPLACE INTO products (id,cat,name,price,unit,badge,descr,specs,options,active) VALUES ('tm-modular-negru','tigla-metalica','Țiglă metalică modulară Onduline Black',64,'mp',NULL,'Panouri modulare de 1.2m, ușor de transportat și montat, finisaj negru mat elegant.','{"Grosime":"0.5 mm","Modul":"1200 x 420 mm","Culoare":"Negru mat RAL 9005","Garanție":"20 ani","Greutate":"5.0 kg/mp"}',NULL,1);
INSERT OR REPLACE INTO products (id,cat,name,price,unit,badge,descr,specs,options,active) VALUES ('tf-standing-seam','tabla-faltuita','Tablă fălțuită Standing Seam 0.5mm',71,'mp','Nou','Sistem standing seam cu fălțuire dublă, aspect liniar modern, fără șuruburi vizibile.','{"Grosime":"0.5 mm","Lățime modul":"510 mm","Culoare":"Gri argintiu RAL 9006","Garanție":"30 ani","Fălțuire":"Dublă 25mm"}',NULL,1);
INSERT OR REPLACE INTO products (id,cat,name,price,unit,badge,descr,specs,options,active) VALUES ('tf-click-antracit','tabla-faltuita','Tablă prefălțuită Click Antracit',66.5,'mp',NULL,'Panouri prefălțuite cu îmbinare tip click, montaj rapid fără mașină de fălțuit.','{"Grosime":"0.5 mm","Lățime modul":"530 mm","Culoare":"Antracit RAL 7016","Garanție":"25 ani","Îmbinare":"Click snap-lock"}',NULL,1);
INSERT OR REPLACE INTO products (id,cat,name,price,unit,badge,descr,specs,options,active) VALUES ('tf-cupru-look','tabla-faltuita','Tablă fălțuită aspect cupru 0.6mm',98,'mp','Premium','Finisaj special aspect cupru pentru proiecte arhitecturale deosebite.','{"Grosime":"0.6 mm","Lățime modul":"510 mm","Culoare":"Aspect cupru","Garanție":"30 ani","Fălțuire":"Dublă"}',NULL,1);
INSERT OR REPLACE INTO products (id,cat,name,price,unit,badge,descr,specs,options,active) VALUES ('ps-40mm','panouri-sandwich','Panou sandwich acoperiș 40mm PUR',89,'mp','Best seller','Panou termoizolant cu miez poliuretanic de 40mm, 5 cute, pentru hale și anexe.','{"Grosime miez":"40 mm","Izolație":"Poliuretan PUR","Lățime utilă":"1000 mm","U":"0.53 W/mpK","Culoare":"Alb RAL 9002"}',NULL,1);
INSERT OR REPLACE INTO products (id,cat,name,price,unit,badge,descr,specs,options,active) VALUES ('ps-60mm','panouri-sandwich','Panou sandwich acoperiș 60mm PIR',118,'mp',NULL,'Miez PIR ignifug de 60mm, izolare termică superioară și clasă de foc B.','{"Grosime miez":"60 mm","Izolație":"PIR ignifug","Lățime utilă":"1000 mm","U":"0.36 W/mpK","Reacție foc":"B-s1,d0"}',NULL,1);
INSERT OR REPLACE INTO products (id,cat,name,price,unit,badge,descr,specs,options,active) VALUES ('ps-100mm','panouri-sandwich','Panou sandwich acoperiș 100mm PIR',156,'mp',NULL,'Cea mai bună izolare din gamă, recomandat pentru spații locuibile și frigorifice.','{"Grosime miez":"100 mm","Izolație":"PIR ignifug","Lățime utilă":"1000 mm","U":"0.22 W/mpK","Reacție foc":"B-s1,d0"}',NULL,1);
INSERT OR REPLACE INTO products (id,cat,name,price,unit,badge,descr,specs,options,active) VALUES ('sp-jgheab-150','sistem-pluvial','Jgheab semicircular Ø150 din oțel',34,'ml',NULL,'Jgheab din oțel vopsit în câmp electrostatic, tronson 3m, prindere cu cârlige incluse.','{"Diametru":"Ø150 mm","Material":"Oțel 0.6mm","Lungime":"3 m/buc","Culoare":"Maro RAL 8017","Garanție":"15 ani"}',NULL,1);
INSERT OR REPLACE INTO products (id,cat,name,price,unit,badge,descr,specs,options,active) VALUES ('sp-burlan-100','sistem-pluvial','Burlan rotund Ø100 din oțel',29.5,'ml',NULL,'Burlan din oțel asortat jgheabului Ø150, tronson 3m, coliere de prindere incluse.','{"Diametru":"Ø100 mm","Material":"Oțel 0.6mm","Lungime":"3 m/buc","Culoare":"Maro RAL 8017","Garanție":"15 ani"}',NULL,1);
INSERT OR REPLACE INTO products (id,cat,name,price,unit,badge,descr,specs,options,active) VALUES ('sp-kit-casa','sistem-pluvial','Kit sistem pluvial casă (pachet complet)',1290,'set','Economic','Pachet complet pentru o casă medie: jgheaburi, burlane, coturi, racorduri și accesorii.','{"Acoperire":"~120 mp acoperiș","Jgheab":"Ø150 x 24 ml","Burlan":"Ø100 x 16 ml","Culoare":"La alegere","Garanție":"15 ani"}',NULL,1);
INSERT OR REPLACE INTO products (id,cat,name,price,unit,badge,descr,specs,options,active) VALUES ('ac-coama','accesorii','Coamă rotundă cu garnitură (2m)',38,'buc',NULL,'Coamă rotundă din tablă asortată, cu garnitură de etanșare inclusă, lungime 2m.','{"Lungime":"2 m","Material":"Oțel 0.5mm","Culoare":"La alegere","Include":"Garnitură burete"}',NULL,1);
INSERT OR REPLACE INTO products (id,cat,name,price,unit,badge,descr,specs,options,active) VALUES ('ac-parazapada','accesorii','Parazăpadă bară (set 3m)',145,'set',NULL,'Sistem de parazăpezi cu bară dublă și console, previne alunecarea zăpezii de pe acoperiș.','{"Lungime":"3 m","Console":"4 buc incluse","Material":"Oțel zincat","Sarcină":"Mare"}',NULL,1);
INSERT OR REPLACE INTO products (id,cat,name,price,unit,badge,descr,specs,options,active) VALUES ('ac-suruburi','accesorii','Șuruburi autoforante cu garnitură (250 buc)',89,'cutie','Best seller','Șuruburi autoforante 4.8x35mm cu garnitură EPDM, cap vopsit, cutie 250 bucăți.','{"Dimensiune":"4.8 x 35 mm","Cantitate":"250 buc","Garnitură":"EPDM","Cap":"Vopsit la culoare"}',NULL,1);
INSERT OR REPLACE INTO products (id,cat,name,price,unit,badge,descr,specs,options,active) VALUES ('fm-anticondens','folii-membrane','Folie anticondens 3 straturi (75mp)',320,'rolă',NULL,'Folie anticondens cu strat absorbant, protejează șarpanta de umezeală. Rolă 1.5x50m.','{"Suprafață":"75 mp/rolă","Straturi":"3","Gramaj":"150 g/mp","Dimensiuni":"1.5 x 50 m"}',NULL,1);
INSERT OR REPLACE INTO products (id,cat,name,price,unit,badge,descr,specs,options,active) VALUES ('fm-difuzie','folii-membrane','Membrană difuzie hidroizolantă 150g (75mp)',415,'rolă','Premium','Membrană traspirantă de înaltă difuzie, permeabilă la vapori și impermeabilă la apă.','{"Suprafață":"75 mp/rolă","Sd":"0.02 m","Gramaj":"150 g/mp","Coloană apă":"> 2000 mm"}',NULL,1);
